#!/bin/bash

function is_prime(){
 if [[ $1 -eq 2 ]] || [[ $1 -eq 3 ]]; then 
   return 1 #this is prime
 fi 
  if [[ $(($1 % 2)) -eq 0 ]] || [[ $(($1 % 3)) -eq 0 ]];then
   return 0 #is not prime
 fi
 i=5; w=q2
 while [[ $((i * i)) -le $1 ]]; do
  if [[ $(($1 % i)) -eq 0 ]]; then
    return 0
   fi 
   i=$((i + w))
   w=$((6 - w))
  done
  return 1 #prime
}
is_prime $1
if [[ $? -eq 0 ]]; then
  echo not prime
else
  echo it is prime
fi
